name: "Release artifacts"

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  REGISTRY: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com
  IMAGE: nitro-node-x
  DOCKERFILE: Dockerfile

jobs:
  build-artifacts:
    strategy:
      matrix:
        arch: [ amd64 ]
    runs-on: [self-hosted, "${{ matrix.arch }}"]
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          clean: true
          app_id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private_key: ${{ secrets.RELEASE_MANAGER_APP_SECRET }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set env
        run: |
          echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.arch }}-${{ env.REVISION }}
          build-args: ACCESS_TOKEN=${{ steps.generate-token.outputs.token }}
          provenance: false